# Site setting
title: 阔落的博客

highlighter: rouge
markdown: kramdown
toc_levels: 1..2
timezone: Asia/Shanghai
kramdown:
    input: GFM
    syntax_highlighter: rouge
data_dir: data
includes_dir: pages/includes
layouts_dir: pages/layouts
sass:
    sass_dir: assets/scss
    style: compressed

github:
    username: 'kuoluo1995'
    repo: 'kuoluo1995.github.io'
    clientId: c9f6380ba6482d9e19a4
    clientSecret: 2ea7c5989d0983e2d35c3e3b21e7acbc9d81e5b9

baidu_id: dbb88ff54ff24c582ace1c91136e8461
google_id: UA-144583819-1
footer_description: