# Site setting
title: 阔落的博客

highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
data_dir: data
includes_dir: pages/includes
layouts_dir: pages/layouts
sass:
    sass_dir: assets/scss
    style: compressed


baidu_id: dbb88ff54ff24c582ace1c91136e8461
footer_description: 不会写前端的Java程序员，不是个好的算法工程师